apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "plngxftpbridge.fullname" . }}"
  labels:
    {{- include "plngxftpbridge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "plngxftpbridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        secrets-hash: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plngxftpbridge.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.Version) }}"
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            - name: CRON_SCHEDULE
              value: "{{ .Values.interval }}"
            - name: FTP_HOST
              value: "{{ required "ftp.host is required" .Values.ftp.host }}"
            - name: FTP_USERNAME
              value: "{{ required "ftp.user is required" .Values.ftp.user }}"
            - name: FTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plngxftpbridge.fullname" . }}
                  key: ftp-password
            - name: FTP_PATH
              value: "{{ .Values.ftp.path }}"
            - name: PAPERLESS_URL
              value: "{{ .Values.paperless.url }}"
            - name: PAPERLESS_USER
              value: "{{ required "paperless.username is required" .Values.paperless.username }}"
            - name: PAPERLESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plngxftpbridge.fullname" . }}
                  key: paperless-password
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      restartPolicy: Always
