apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "plngxftpbridge.fullname" . }}"
type: Opaque
stringData:
  {{- range $i, $account := .Values.ftp.accounts }}
  {{- if $account.password }}
  ftp-account-{{ $i }}-password: {{ $account.password | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.paperless.password }}
  paperless-password: {{ .Values.paperless.password | quote }}
  {{- end }}
