apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "plngxftpbridge.fullname" . }}"
type: Opaque
stringData:
  ftp-password: {{ required "ftp.password is required" .Values.ftp.password }}
  paperless-password: {{ required "paperless.password is required" .Values.paperless.password }}
