{{- if or .Values.ftp.password .Values.paperless.password }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "plngxftpbridge.fullname" . }}"
type: Opaque
stringData:
  {{- if .Values.ftp.password }}
  ftp-password: {{ required "ftp.password is required" .Values.ftp.password | quote }}
  {{- end }}
  {{- if .Values.paperless.password }}
  paperless-password: {{ required "paperless.password is required" .Values.paperless.password | quote }}
  {{- end }}
{{- end }}
