# logLevel for the bridge - DEBUG, INFO, WARNING, ERROR
logLevel: INFO

# schedule to check for new documents every 5 minutes
interval: "*/5 * * * *"

# ftp configuration where to fetch the documents
ftp:
  # e.g. ftp.example.org:21
  host: ""
  user: ""
  # password for ftp connection
  password: ""
  # passwordExistingSecret is used to reference an existing secret in the same namespace
  passwordExistingSecret:
    name: ""
    key: ""
  path: "."

# paperless-ngx configuration to send documents to
paperless:
  # url with protocol but no API endpoint
  url: "http://paperless-ngx:8000"
  username: ""
  # password for paperless-ngx
  password: ""
  # passwordExistingSecret is used to reference an existing secret in the same namespace
  passwordExistingSecret:
    name: ""
    key: ""

# image used for bridge
image:
  repository: ghcr.io/taskmedia/paperlessngx-ftp-bridge-image
  tag: ""
  pullPolicy: Always

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}
